dataset_path: /home/jupyter/data_files/BLINK
dataset_name: "IQ_Test"
task: "blink_iqtest"
dataset_kwargs:
  token: True

test_split: val
output_type: generate_until
doc_to_visual: !function utils.blink_doc_to_visual
doc_to_text: !function utils.blink_doc_to_text
doc_to_target: !function utils.blink_doc_to_target
process_results: !function utils.blink_process_results


generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: False

filter_list:
  - name: "flexible-extract"
    filter:
      - function: !function utils.MultiChoiceRegexFilter
        group_select: 0
        ignore_case: true
        ignore_punctuation: true
        regex_pattern: "([A-Z])\\."

metric_list:
  - metric: blink_score_overall
    aggregation: !function utils.blink_aggregation 
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true

metadata:
  - version: 0.0

lmms_eval_specific_kwargs:
  default:
    prompt_mode: "videor1"
  qwen2_5_vl_query:
    prompt_mode: "latents"
  qwen2_5_vl_mmlatent:
    prompt_mode: "latents"
  qwen2_5_vl_mmlatentsample:
    prompt_mode: "latents"
  qwen2_5_vl_mmlatent_imonly:
    prompt_mode: "latents"
  qwen2_5_vl_mmlatentdiscrete:
    prompt_mode: "latents"