dataset_path: /home/jupyter/data_files/VSI-Bench
dataset_kwargs:
  token: False
  cache_dir: /home/jupyter/data_files/VSI-Bench
  video: True
task: vsibench
test_split: test
output_type: generate_until
process_docs: !function utils.process_docs
doc_to_visual: !function utils.vsibench_doc_to_visual
doc_to_text: !function utils.vsibench_doc_to_text
doc_to_target: "ground_truth"

generation_kwargs:
  max_new_tokens: 1024
  temperature: 0.1
  top_p: 0.001
  num_beams: 1
  do_sample: True
# The return value of process_results will be used by metrics
process_results: !function utils.vsibench_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: vsibench_score
    aggregation: !function utils.vsibench_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    prompt_mode: "videor1"
  qwen2_5_vl_query:
    prompt_mode: "latents"
  qwen2_5_vl_mmlatent:
    prompt_mode: "latents"
  qwen2_5_vl_mmlatentsample:
    prompt_mode: "latents"
  qwen2_5_vl_mmlatent_imonly:
    prompt_mode: "latents"
  qwen2_5_vl_mmlatentdiscrete:
    prompt_mode: "latents"


metadata:
  - version: 0.0
