dataset_path: lmms-lab/VQAv2
dataset_kwargs:
  token: True

task: "vqav2_val"
test_split: validation
output_type: generate_until
doc_to_visual: !function utils.vqav2_doc_to_visual
doc_to_text: !function utils.vqav2_doc_to_text
doc_to_target: "answer"
process_results: !function utils.vqav2_process_results

generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: False

metric_list:
  - metric: vqav2_accuracy
    aggregation: !function utils.vqav2_aggregate_results
    higher_is_better: true

metadata:
  - version: 0.0

lmms_eval_specific_kwargs:
  default:
    prompt_mode: "sft"
  qwen2_5_vl_query:
    prompt_mode: "latents"
  qwen2_5_vl_mmlatent:
    prompt_mode: "latents"
  qwen2_5_vl_mmlatentsample:
    prompt_mode: "latents"
  qwen2_5_vl_mmlatent_imonly:
    prompt_mode: "latents"
  qwen2_5_vl_mmlatentdiscrete:
    prompt_mode: "latents"
